### PR TITLE
Allow shallow clone of Git repos, and enable by default

### PR DESCRIPTION
**Pull request by Smaug123**
Not yet remotely got this ready to merge, hence the lack of checklist-filling. Will do this after eating.

Make sure you have:

  * [ ] reviewed and applied the coding style: [coding](https://github.com/leanprover/mathlib/blob/master/docs/style.md), [naming](https://github.com/leanprover/mathlib/blob/master/docs/naming.md)
  * [x] for tactics:
     * [x] added or adapted documentation in [tactics.md](https://github.com/leanprover/mathlib/blob/master/docs/tactics.md)
     * [x] write an example of use of the new feature in [tactics.lean](https://github.com/leanprover/mathlib/blob/master/tests/tactics.lean)
  * [x] make sure definitions and lemmas are put in the right files
  * [x] make sure definitions and lemmas are not redundant

If this PR is related to a discussion on Zulip, please include a link in the discussion.

For reviewers: [code review check list](https://github.com/leanprover/mathlib/blob/master/docs/code-review.md)

### CODE REVIEW

**Comment by Smaug123** [comment]
TODO: also test that we can use the shallow=false option.

**Comment by Smaug123** [comment]
Sorry about all these commits. The pre-merge tests are the only way of running this I have yet got to work.

**Comment by Smaug123** [comment]
I can actually feel my life draining away here :P

**Comment by PatrickMassot** [comment]
I'm closing since this has been a draft with no activity since May.

**Pull request closed without merging**
