### PR TITLE
Raise exceptions on leanpkg and git errors

### PR DESCRIPTION
**Pull request by Vtec234**
When running `leanproject` in CI (and arguably in general), we want it to exit with a non-zero code if the command fails. Here, I make calls to `subprocess.run` raise an exception if the tool fails where that makes sense, so that the exception handler is called and `leanproject` overall exits with an error. Otherwise, builds that clearly failed ([e.g. here](https://github.com/b-mehta/topos/runs/556155330)) still get a green tick.

### CODE REVIEW

**Comment by PatrickMassot** [comment]
I'm sorry I've neglected this PR, I should have merged it before the import graph stuff. Could you rebase and force push? I'll merge it right away.

**Comment by Vtec234** [comment]
@PatrickMassot done!

**Comment by PatrickMassot** [comment]
GitHub still complains "This branch cannot be rebased due to conflicts".

**Comment by Vtec234** [comment]
That's strange, there's a green tick here. I also just tried `git merge errors` into a copy of current `master` locally and that works. Are you trying to merge this PR via the squash or the merge method? Perhaps it's just the rebase way that doesn't work.

**Comment by PatrickMassot** [comment]
Indeed I didn't notice I could switch from "rebase and merge" to "squash and merge". Sorry about the noise.

**Pull request merged**
