### PR TITLE
Add an automatic release-on-tag-push GHA.

### PR DESCRIPTION
**Pull request by Julian**
In case you feel like taking me up on https://github.com/leanprover-community/mathlib-tools/pull/86#issuecomment-717572299 :)

If you want to use this, go to https://pypi.org/manage/account/token/, call it `mathlib-tools` or whatever, give it scope to upload to mathlib-tools, paste it here in GitHub in the Settings menu of this repo in your secrets, call it `pypi_password`, then when you bump a version, `git tag -a v0.11.0 -m "New Release"`, and when you push the tag it'll autoupload to PyPI.

### CODE REVIEW

**Comment by eric-wieser** [comment]
This change looks good to me; is there a reason you closed it?

**Comment by Julian** [comment]
Patrick mentioned he wasn't so interested.

**Comment by eric-wieser** [comment]
I wonder if the increased volume of port-related PRs and corresponding pressure to make more releases might adjust the balance there (or if we [shouldn't be making those PRs here in the first place](https://leanprover.zulipchat.com/#narrow/stream/287929-mathlib4/topic/Do.20port.20status.20scripts.20belong.20in.20mathlibtools.20or.20mathlib.3F/near/311073629))

**Comment by Julian** [comment]
(I agree with your suggestion there I think) but if there's consensus, happy to re-open this, revisit it, or to have you or anyone "take it and merge". Lemme know whatever'd help.

**Pull request closed without merging**
