### PR TITLE
import-graph: write raw dot file to ".rawdot" without layout info

### PR DESCRIPTION
**Pull request by m4lvin**
fixes https://github.com/leanprover-community/mathlib-tools/issues/53

### CODE REVIEW

**Comment by jcommelin** [comment]
This looks good to me.

**Comment by jcommelin** [comment]
@m4lvin Do you know what's up with the failing check?

**Comment by m4lvin** [comment]
I am afraid I do not know anything about the failing Pyinstaller check and now `The logs for this run have expired and are no longer available.` — is there a way to re-run the checks to investigate it?

**Comment by jcommelin** [comment]
Merging master, or pushing an empty commit will certainly trigger CI to build again.

**Comment by m4lvin** [comment]
I think the CI is failing due to some problem between pip and PyInstaller which is completely unrelated to the changes in the PR here. The other recent commit https://github.com/leanprover-community/mathlib-tools/commit/c24c0c5b5e10a0164263a2e20cba18dc964a86fe has exactly the same CI failure.

My knowledge of pip and python packages is too limited to debug this properly. I thought it might be related to the case-sensitive `pyinstaller` vs `PyInstaller` or https://github.com/pypa/pip/issues/6163 - in particular this says it should be fixed in pip 19.0.2 which was in 2019 and the github actions runner for windows seems to use pip 22.2.2 as per https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md

**Pull request merged**
